Repository wallace0003/projeto-4, pull requests merged in 2024-05, with the labels that each got.

#9 Listar cliente
  bank.c
  bank.h
  main.c
Labels: enhancement

#10 função depositar
  bank.c
  bank.h
  main.c
Labels: enhancement

#11 Debito
  bank.c
  bank.h
  main.c
Labels: enhancement

#12 função transferencia
  bank.c
  bank.h
  main.c
Labels: enhancement

#14 bug de transferencia corrigido
  bank.c
Labels: bug

#16 função de extrato foi um sucesso
  bank.c
  bank.h
  main.c
Labels: enhancement

#17 tarifa adicionada aos extratos
  bank.c
  bank.h
Labels: bug, enhancement

#19 salvar-binário criado
  bank.c
  bank.h
  main.c
Labels: enhancement

#22 carregar binário foi um sucesso
  bank.c
  bank.h
  main.c
Labels: enhancement

#24 Realizado a documentação do projeto 4
  README.md
Labels: documentation

#26 Bugs
  bank.c
Labels: bug

#27 Bugs
  bank.c
  bank.h
Labels: bug

#28 corrigindo cpf de int pra long
  bank.c
Labels: bug
